#RI-5118 - update readme
RedisInsight/Tutorials pull request #31
Opened 2024-01-29 08:28 UTC by romansergeenkosofteq

2024-01-29 14:06 UTC, ViktarStarastsenka requested changes

2024-01-29 14:06 UTC, ViktarStarastsenka commented on README.md
>  ```
will `auto=false` still work?

2024-01-29 14:06 UTC, ViktarStarastsenka commented on README.md
>  Manifest file should start with single Node and should have properties described
let's update the file with examples

2024-01-29 14:06 UTC, ViktarStarastsenka commented on README.md
please add information on what fields are displayed in RedisInsight and what are not

2024-01-31 14:47 UTC, dwdougherty requested changes
Hi Viktar. Just a few copy-edits.

2024-01-31 14:47 UTC, dwdougherty commented on README.md
> +You can use tutorials already embedded in RedisInsight to explore powerful Redis capabilities, or create your own custom tutorials to present your experience using RedisInsight and share them with ot
```suggestion
Tutorials are interactive documents that contain helpful use cases, comments, and related demonstrations of Redis features to help you level up your Redis game.
You can use RedisInsight's built-in tutorials to explore powerful Redis capabilities or create custom tutorials to present your experience using RedisInsight and share them with others.
```

2024-01-31 14:47 UTC, dwdougherty commented on README.md
> +If you want to share your own tutorials - add the `redis-tutorials` label to your GitHub repository so other other GitHub users can find and learn your experience.
```suggestion
If you want to share your custom tutorials with others, add the `redis-tutorials` label to your GitHub repository so other GitHub users can find them and learn your experience.
```

2024-01-31 14:47 UTC, dwdougherty commented on README.md
> +- click the "Upload Tutorial" button and select the example
```suggestion
- Download this example.
- Open RedisInsight.
- Navigate to the Insights panel (top right corner).
- Find the "My Tutorials" section on the "Explore" tab.
- Click the "Upload Tutorial" button and select the example.
```

2024-01-31 14:47 UTC, dwdougherty commented on README.md
> +If you would like to add a button to run commands, use Redis Code block that is almost the same as for the [Fenced Code Block](https://www.markdownguide.org/extended-syntax/#fenced-code-blocks), but
```suggestion
If you would like to add a button to run commands, use a Redis Code block that is almost the same as a [Fenced Code Block](https://www.markdownguide.org/extended-syntax/#fenced-code-blocks), but you need to specify `redis` as the language and write a label next to it (see the `Create` button example below).
```

2024-01-31 15:38 UTC, ViktarStarastsenka approved these changes
LGTM

2024-01-31 15:48 UTC, dwdougherty approved these changes

2024-01-31 15:53 UTC, merged